version: '3.8'

services:
  orthanc:
    image: orthancteam/orthanc:current
    container_name: orthanc-arm64
    ports:
      - "4242:4242"  # DICOM port
      - "8042:8042"  # HTTP port
    volumes:
      - ./orthanc-config/orthanc.json:/etc/orthanc/orthanc.json  # Config file
      - orthanc_data:/var/lib/orthanc/db  # Persistent storage for DICOM files
    restart: always

volumes:
  orthanc_data:
    driver: local